/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.services.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.services.model.AdCategory;

import com.services.service.AdCategoryLocalServiceUtil;

/**
 * The extended model base implementation for the AdCategory service. Represents a row in the &quot;AL_AdCategory&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AdCategoryImpl}.
 * </p>
 *
 * @author Ankur Srivastava
 * @see AdCategoryImpl
 * @see com.services.model.AdCategory
 * @generated
 */
public abstract class AdCategoryBaseImpl extends AdCategoryModelImpl
	implements AdCategory {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a ad category model instance should use the {@link AdCategory} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			AdCategoryLocalServiceUtil.addAdCategory(this);
		}
		else {
			AdCategoryLocalServiceUtil.updateAdCategory(this);
		}
	}
}