/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.services.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the AdCategory service. Represents a row in the &quot;AL_AdCategory&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.services.model.impl.AdCategoryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.services.model.impl.AdCategoryImpl}.
 * </p>
 *
 * @author Ankur Srivastava
 * @see AdCategory
 * @see com.services.model.impl.AdCategoryImpl
 * @see com.services.model.impl.AdCategoryModelImpl
 * @generated
 */
public interface AdCategoryModel extends BaseModel<AdCategory> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ad category model instance should use the {@link AdCategory} interface instead.
	 */

	/**
	 * Returns the primary key of this ad category.
	 *
	 * @return the primary key of this ad category
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this ad category.
	 *
	 * @param primaryKey the primary key of this ad category
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the category ID of this ad category.
	 *
	 * @return the category ID of this ad category
	 */
	public long getCategoryId();

	/**
	 * Sets the category ID of this ad category.
	 *
	 * @param categoryId the category ID of this ad category
	 */
	public void setCategoryId(long categoryId);

	/**
	 * Returns the category name of this ad category.
	 *
	 * @return the category name of this ad category
	 */
	@AutoEscape
	public String getCategoryName();

	/**
	 * Sets the category name of this ad category.
	 *
	 * @param categoryName the category name of this ad category
	 */
	public void setCategoryName(String categoryName);

	/**
	 * Returns the category status of this ad category.
	 *
	 * @return the category status of this ad category
	 */
	public boolean getCategoryStatus();

	/**
	 * Returns <code>true</code> if this ad category is category status.
	 *
	 * @return <code>true</code> if this ad category is category status; <code>false</code> otherwise
	 */
	public boolean isCategoryStatus();

	/**
	 * Sets whether this ad category is category status.
	 *
	 * @param categoryStatus the category status of this ad category
	 */
	public void setCategoryStatus(boolean categoryStatus);

	/**
	 * Returns the created date of this ad category.
	 *
	 * @return the created date of this ad category
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this ad category.
	 *
	 * @param createdDate the created date of this ad category
	 */
	public void setCreatedDate(Date createdDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.services.model.AdCategory adCategory);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.services.model.AdCategory> toCacheModel();

	@Override
	public com.services.model.AdCategory toEscapedModel();

	@Override
	public com.services.model.AdCategory toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}