/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.services.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the AdCity service. Represents a row in the &quot;AL_AdCity&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.services.model.impl.AdCityModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.services.model.impl.AdCityImpl}.
 * </p>
 *
 * @author Ankur Srivastava
 * @see AdCity
 * @see com.services.model.impl.AdCityImpl
 * @see com.services.model.impl.AdCityModelImpl
 * @generated
 */
public interface AdCityModel extends BaseModel<AdCity> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ad city model instance should use the {@link AdCity} interface instead.
	 */

	/**
	 * Returns the primary key of this ad city.
	 *
	 * @return the primary key of this ad city
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this ad city.
	 *
	 * @param primaryKey the primary key of this ad city
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the city ID of this ad city.
	 *
	 * @return the city ID of this ad city
	 */
	public long getCityId();

	/**
	 * Sets the city ID of this ad city.
	 *
	 * @param cityId the city ID of this ad city
	 */
	public void setCityId(long cityId);

	/**
	 * Returns the city name of this ad city.
	 *
	 * @return the city name of this ad city
	 */
	@AutoEscape
	public String getCityName();

	/**
	 * Sets the city name of this ad city.
	 *
	 * @param cityName the city name of this ad city
	 */
	public void setCityName(String cityName);

	/**
	 * Returns the state name of this ad city.
	 *
	 * @return the state name of this ad city
	 */
	@AutoEscape
	public String getStateName();

	/**
	 * Sets the state name of this ad city.
	 *
	 * @param stateName the state name of this ad city
	 */
	public void setStateName(String stateName);

	/**
	 * Returns the city status of this ad city.
	 *
	 * @return the city status of this ad city
	 */
	public boolean getCityStatus();

	/**
	 * Returns <code>true</code> if this ad city is city status.
	 *
	 * @return <code>true</code> if this ad city is city status; <code>false</code> otherwise
	 */
	public boolean isCityStatus();

	/**
	 * Sets whether this ad city is city status.
	 *
	 * @param cityStatus the city status of this ad city
	 */
	public void setCityStatus(boolean cityStatus);

	/**
	 * Returns the popular of this ad city.
	 *
	 * @return the popular of this ad city
	 */
	public boolean getPopular();

	/**
	 * Returns <code>true</code> if this ad city is popular.
	 *
	 * @return <code>true</code> if this ad city is popular; <code>false</code> otherwise
	 */
	public boolean isPopular();

	/**
	 * Sets whether this ad city is popular.
	 *
	 * @param popular the popular of this ad city
	 */
	public void setPopular(boolean popular);

	/**
	 * Returns the created date of this ad city.
	 *
	 * @return the created date of this ad city
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this ad city.
	 *
	 * @param createdDate the created date of this ad city
	 */
	public void setCreatedDate(Date createdDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.services.model.AdCity adCity);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.services.model.AdCity> toCacheModel();

	@Override
	public com.services.model.AdCity toEscapedModel();

	@Override
	public com.services.model.AdCity toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}