/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.services.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the AdCountry service. Represents a row in the &quot;AL_AdCountry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.services.model.impl.AdCountryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.services.model.impl.AdCountryImpl}.
 * </p>
 *
 * @author Ankur Srivastava
 * @see AdCountry
 * @see com.services.model.impl.AdCountryImpl
 * @see com.services.model.impl.AdCountryModelImpl
 * @generated
 */
public interface AdCountryModel extends BaseModel<AdCountry> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ad country model instance should use the {@link AdCountry} interface instead.
	 */

	/**
	 * Returns the primary key of this ad country.
	 *
	 * @return the primary key of this ad country
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this ad country.
	 *
	 * @param primaryKey the primary key of this ad country
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the country ID of this ad country.
	 *
	 * @return the country ID of this ad country
	 */
	public long getCountryId();

	/**
	 * Sets the country ID of this ad country.
	 *
	 * @param countryId the country ID of this ad country
	 */
	public void setCountryId(long countryId);

	/**
	 * Returns the country name of this ad country.
	 *
	 * @return the country name of this ad country
	 */
	@AutoEscape
	public String getCountryName();

	/**
	 * Sets the country name of this ad country.
	 *
	 * @param countryName the country name of this ad country
	 */
	public void setCountryName(String countryName);

	/**
	 * Returns the country status of this ad country.
	 *
	 * @return the country status of this ad country
	 */
	public boolean getCountryStatus();

	/**
	 * Returns <code>true</code> if this ad country is country status.
	 *
	 * @return <code>true</code> if this ad country is country status; <code>false</code> otherwise
	 */
	public boolean isCountryStatus();

	/**
	 * Sets whether this ad country is country status.
	 *
	 * @param countryStatus the country status of this ad country
	 */
	public void setCountryStatus(boolean countryStatus);

	/**
	 * Returns the created date of this ad country.
	 *
	 * @return the created date of this ad country
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this ad country.
	 *
	 * @param createdDate the created date of this ad country
	 */
	public void setCreatedDate(Date createdDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.services.model.AdCountry adCountry);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.services.model.AdCountry> toCacheModel();

	@Override
	public com.services.model.AdCountry toEscapedModel();

	@Override
	public com.services.model.AdCountry toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}