/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.services.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the AdListing service. Represents a row in the &quot;AL_AdListing&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.services.model.impl.AdListingModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.services.model.impl.AdListingImpl}.
 * </p>
 *
 * @author Ankur Srivastava
 * @see AdListing
 * @see com.services.model.impl.AdListingImpl
 * @see com.services.model.impl.AdListingModelImpl
 * @generated
 */
public interface AdListingModel extends BaseModel<AdListing> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ad listing model instance should use the {@link AdListing} interface instead.
	 */

	/**
	 * Returns the primary key of this ad listing.
	 *
	 * @return the primary key of this ad listing
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this ad listing.
	 *
	 * @param primaryKey the primary key of this ad listing
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ad ID of this ad listing.
	 *
	 * @return the ad ID of this ad listing
	 */
	public long getAdId();

	/**
	 * Sets the ad ID of this ad listing.
	 *
	 * @param adId the ad ID of this ad listing
	 */
	public void setAdId(long adId);

	/**
	 * Returns the ad title of this ad listing.
	 *
	 * @return the ad title of this ad listing
	 */
	@AutoEscape
	public String getAdTitle();

	/**
	 * Sets the ad title of this ad listing.
	 *
	 * @param adTitle the ad title of this ad listing
	 */
	public void setAdTitle(String adTitle);

	/**
	 * Returns the ad description of this ad listing.
	 *
	 * @return the ad description of this ad listing
	 */
	@AutoEscape
	public String getAdDescription();

	/**
	 * Sets the ad description of this ad listing.
	 *
	 * @param adDescription the ad description of this ad listing
	 */
	public void setAdDescription(String adDescription);

	/**
	 * Returns the ad cat ID of this ad listing.
	 *
	 * @return the ad cat ID of this ad listing
	 */
	public long getAdCatId();

	/**
	 * Sets the ad cat ID of this ad listing.
	 *
	 * @param adCatId the ad cat ID of this ad listing
	 */
	public void setAdCatId(long adCatId);

	/**
	 * Returns the ad service type of this ad listing.
	 *
	 * @return the ad service type of this ad listing
	 */
	@AutoEscape
	public String getAdServiceType();

	/**
	 * Sets the ad service type of this ad listing.
	 *
	 * @param adServiceType the ad service type of this ad listing
	 */
	public void setAdServiceType(String adServiceType);

	/**
	 * Returns the ad country ID of this ad listing.
	 *
	 * @return the ad country ID of this ad listing
	 */
	public long getAdCountryId();

	/**
	 * Sets the ad country ID of this ad listing.
	 *
	 * @param adCountryId the ad country ID of this ad listing
	 */
	public void setAdCountryId(long adCountryId);

	/**
	 * Returns the ad city ID of this ad listing.
	 *
	 * @return the ad city ID of this ad listing
	 */
	public long getAdCityId();

	/**
	 * Sets the ad city ID of this ad listing.
	 *
	 * @param adCityId the ad city ID of this ad listing
	 */
	public void setAdCityId(long adCityId);

	/**
	 * Returns the user ID of this ad listing.
	 *
	 * @return the user ID of this ad listing
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this ad listing.
	 *
	 * @param userId the user ID of this ad listing
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this ad listing.
	 *
	 * @return the user uuid of this ad listing
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this ad listing.
	 *
	 * @param userUuid the user uuid of this ad listing
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the ad user name of this ad listing.
	 *
	 * @return the ad user name of this ad listing
	 */
	@AutoEscape
	public String getAdUserName();

	/**
	 * Sets the ad user name of this ad listing.
	 *
	 * @param adUserName the ad user name of this ad listing
	 */
	public void setAdUserName(String adUserName);

	/**
	 * Returns the ad user email of this ad listing.
	 *
	 * @return the ad user email of this ad listing
	 */
	@AutoEscape
	public String getAdUserEmail();

	/**
	 * Sets the ad user email of this ad listing.
	 *
	 * @param adUserEmail the ad user email of this ad listing
	 */
	public void setAdUserEmail(String adUserEmail);

	/**
	 * Returns the ad user phone of this ad listing.
	 *
	 * @return the ad user phone of this ad listing
	 */
	@AutoEscape
	public String getAdUserPhone();

	/**
	 * Sets the ad user phone of this ad listing.
	 *
	 * @param adUserPhone the ad user phone of this ad listing
	 */
	public void setAdUserPhone(String adUserPhone);

	/**
	 * Returns the ad status of this ad listing.
	 *
	 * @return the ad status of this ad listing
	 */
	public boolean getAdStatus();

	/**
	 * Returns <code>true</code> if this ad listing is ad status.
	 *
	 * @return <code>true</code> if this ad listing is ad status; <code>false</code> otherwise
	 */
	public boolean isAdStatus();

	/**
	 * Sets whether this ad listing is ad status.
	 *
	 * @param adStatus the ad status of this ad listing
	 */
	public void setAdStatus(boolean adStatus);

	/**
	 * Returns the created date of this ad listing.
	 *
	 * @return the created date of this ad listing
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this ad listing.
	 *
	 * @param createdDate the created date of this ad listing
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the modified date of this ad listing.
	 *
	 * @return the modified date of this ad listing
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this ad listing.
	 *
	 * @param modifiedDate the modified date of this ad listing
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the company ID of this ad listing.
	 *
	 * @return the company ID of this ad listing
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this ad listing.
	 *
	 * @param companyId the company ID of this ad listing
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this ad listing.
	 *
	 * @return the group ID of this ad listing
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this ad listing.
	 *
	 * @param groupId the group ID of this ad listing
	 */
	public void setGroupId(long groupId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.services.model.AdListing adListing);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.services.model.AdListing> toCacheModel();

	@Override
	public com.services.model.AdListing toEscapedModel();

	@Override
	public com.services.model.AdListing toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}