/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.services.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the AdStatsTracker service. Represents a row in the &quot;AL_AdStatsTracker&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.services.model.impl.AdStatsTrackerModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.services.model.impl.AdStatsTrackerImpl}.
 * </p>
 *
 * @author Ankur Srivastava
 * @see AdStatsTracker
 * @see com.services.model.impl.AdStatsTrackerImpl
 * @see com.services.model.impl.AdStatsTrackerModelImpl
 * @generated
 */
public interface AdStatsTrackerModel extends BaseModel<AdStatsTracker> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ad stats tracker model instance should use the {@link AdStatsTracker} interface instead.
	 */

	/**
	 * Returns the primary key of this ad stats tracker.
	 *
	 * @return the primary key of this ad stats tracker
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this ad stats tracker.
	 *
	 * @param primaryKey the primary key of this ad stats tracker
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ad ID of this ad stats tracker.
	 *
	 * @return the ad ID of this ad stats tracker
	 */
	public long getAdId();

	/**
	 * Sets the ad ID of this ad stats tracker.
	 *
	 * @param adId the ad ID of this ad stats tracker
	 */
	public void setAdId(long adId);

	/**
	 * Returns the ad count of this ad stats tracker.
	 *
	 * @return the ad count of this ad stats tracker
	 */
	public long getAdCount();

	/**
	 * Sets the ad count of this ad stats tracker.
	 *
	 * @param adCount the ad count of this ad stats tracker
	 */
	public void setAdCount(long adCount);

	/**
	 * Returns the created date of this ad stats tracker.
	 *
	 * @return the created date of this ad stats tracker
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this ad stats tracker.
	 *
	 * @param createdDate the created date of this ad stats tracker
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the last accessed date of this ad stats tracker.
	 *
	 * @return the last accessed date of this ad stats tracker
	 */
	public Date getLastAccessedDate();

	/**
	 * Sets the last accessed date of this ad stats tracker.
	 *
	 * @param lastAccessedDate the last accessed date of this ad stats tracker
	 */
	public void setLastAccessedDate(Date lastAccessedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.services.model.AdStatsTracker adStatsTracker);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.services.model.AdStatsTracker> toCacheModel();

	@Override
	public com.services.model.AdStatsTracker toEscapedModel();

	@Override
	public com.services.model.AdStatsTracker toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}